-- Hardening after Supabase advisors.
create index organizations_created_by_idx on public.organizations(created_by); create index projects_created_by_idx on public.projects(created_by); create index events_created_by_idx on public.events(created_by);
drop policy if exists "organization creator select" on public.organizations; drop policy if exists "member organization select" on public.organizations;
create policy "organization accessible select" on public.organizations for select to authenticated using ((select auth.uid())=created_by or exists(select 1 from public.organization_memberships m where m.organization_id=id and m.user_id=(select auth.uid()) and m.status='active'));
drop policy if exists "project member rows select" on public.project_memberships; drop policy if exists "org admin project member manage" on public.project_memberships;
create policy "project membership accessible select" on public.project_memberships for select to authenticated using (user_id=(select auth.uid()) or exists(select 1 from public.projects p join public.organization_memberships m on m.organization_id=p.organization_id where p.id=project_id and m.user_id=(select auth.uid()) and m.status='active'));
create policy "project membership admin insert" on public.project_memberships for insert to authenticated with check (exists(select 1 from public.projects p join public.organization_memberships m on m.organization_id=p.organization_id where p.id=project_id and m.user_id=(select auth.uid()) and m.status='active' and (m.role in ('owner','admin') or m.can_manage_members)));
create policy "project membership admin update" on public.project_memberships for update to authenticated using (exists(select 1 from public.projects p join public.organization_memberships m on m.organization_id=p.organization_id where p.id=project_id and m.user_id=(select auth.uid()) and m.status='active' and (m.role in ('owner','admin') or m.can_manage_members))) with check (exists(select 1 from public.projects p join public.organization_memberships m on m.organization_id=p.organization_id where p.id=project_id and m.user_id=(select auth.uid()) and m.status='active' and (m.role in ('owner','admin') or m.can_manage_members)));
create policy "project membership admin delete" on public.project_memberships for delete to authenticated using (exists(select 1 from public.projects p join public.organization_memberships m on m.organization_id=p.organization_id where p.id=project_id and m.user_id=(select auth.uid()) and m.status='active' and (m.role in ('owner','admin') or m.can_manage_members)));
